[package]
name = "fibonnaci-stream"
version = "0.1.0"
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
description = "Stream a Fibonnaci sequence"
license = "Apache-2.0"

[dependencies]
futures = "0.1.18"
